import '../styles/globals.css'
import '../styles/calendaroverride.css'
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faSearch,
  faFlag,
  faInbox,
  faMale,
  faSuitcase,
  faBuilding,
  faLocationArrow,
  faCarAlt,
  faListUl,
  faGrinAlt,
  faBookmark,
  faMapPin,
  faGift,
  faBirthdayCake,
  faGraduationCap,
  faHiking,
  faPencilRuler,
  faFile,
  faBookOpen,
  faFolder,
  faCreditCard,
  faMoneyBillAlt,
  faDumbbell,
  faRunning,
  faUtensils,
  faWineGlass,
  faPills,
  faStethoscope,
  faChair,
  faHome,
  faUniversity,
  faCampground,
  faTv,
  faMusic,
  faTabletAlt,
  faGamepad,
  faHeadphonesAlt,
  faLeaf,
  faCarrot,
  faUserFriends,
  faUsers,
  faPaw,
  faSnowman,
  faFish,
  faShoppingBasket,
  faShoppingCart,
  faShoppingBag,
  faBox,
  faFutbol,
  faBaseballBall,
  faFootballBall,
  faTableTennis,
  faSubway,
  faPlane,
  faShip,
  faUmbrellaBeach,
  faSun,
  faMoon,
  faBasketballBall,
  faTint,
  faSnowflake,
  faFire,
  faTools,
  faCut,
  faDraftingCompass,
  faCode,
  faLightbulb,
  faCommentAlt,
  faShoePrints,
  faAsterisk,
  faSquare,
  faCircle,
  faShapes,
  faBacon,
  faHeart,
  faStar,
  faPlus
} from '@fortawesome/free-solid-svg-icons'
import {
  faCalendar, faCalendarAlt, faClock
} from '@fortawesome/free-regular-svg-icons'

library.add(
  faPlus,
  faClock,
  faSearch,
  faCalendar,
  faFlag,
  faCalendarAlt,
  faInbox,
  faMale,
  faSuitcase,
  faBuilding,
  faLocationArrow,
  faCarAlt,
  faListUl,
  faGrinAlt,
  faBookmark,
  faMapPin,
  faGift,
  faBirthdayCake,
  faGraduationCap,
  faHiking,
  faPencilRuler,
  faFile,
  faBookOpen,
  faFolder,
  faCreditCard,
  faMoneyBillAlt,
  faDumbbell,
  faRunning,
  faUtensils,
  faWineGlass,
  faPills,faStethoscope,faChair,faHome,faUniversity,faCampground,faTv,faMusic,faTabletAlt,faGamepad,
  faHeadphonesAlt,faLeaf,faCarrot,faUserFriends,faUsers,faPaw,faSnowman,faFish,faShoppingBasket,faShoppingCart,
  faShoppingBag,faBox,faFutbol,faBaseballBall,faFootballBall,faTableTennis,faSubway,faPlane,
  faShip,faUmbrellaBeach,faSun,faMoon,faBasketballBall,faTint,faSnowflake,faFire,
  faTools,faCut,faDraftingCompass,faCode,faLightbulb,faCommentAlt,faShoePrints,faAsterisk,
  faSquare,faCircle,faShapes,faBacon,faHeart,faStar,
)
function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}

export default MyApp
